
project_id = "lxhawtndkubaeljbaylp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public", "seo_project"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions]
[functions.admin-users]
verify_jwt = true
[functions.delete-user]
verify_jwt = true
[functions.add-admin-user]
verify_jwt = false
