
project_id = "lxhawtndkubaeljbaylp"

[functions.admin-subscription]
verify_jwt = true

[functions.sync-user]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
